fs/ext4: namei: fix compilation error
from commit 5cdacb4181694713d849f80890bc8cb66143d99d ("ext4: find old entry again if failed to rename whiteout")

../fs/ext4/namei.c:3690:70: error: too few arguments to function call, expected 5, have 4
        old.bh = ext4_find_entry(old.dir, &old.dentry->d_name, &old.de, NULL);
                 ~~~~~~~~~~~~~~~                                            ^
../fs/ext4/namei.c:1663:28: note: 'ext4_find_entry' declared here
static struct buffer_head *ext4_find_entry(struct inode *dir,
                           ^
1 error generated.

Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>